require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.nightfox"
require "user.colorscheme"
require "user.icons"
require "user.cmp"
require "user.navic"
require "user.lsp_inlayhints"
require "user.lsp"
require "user.telescope"
require "user.project"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine1"
require "user.toggleterm"
require "user.dashboard"
require "user.indentline"
require "user.neovide"
require "user.notify"
require "user.functions"
require "user.winbar"
require "user.tabby"
require "user.colorizer"
-- require "user.dap_install"
-- require "user.dap"
require "user.zen-mode"
require "user.hop"
-- require "user.neoscroll"
require "user.surround"
require "user.jaq"
