require("user.hot-reload")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
--[[ require "user.nightfox" ]]
require("user.colorscheme")
require("user.icons")
require("user.cmp")
require("user.navic")
require("user.lsp_inlayhints")
require("user.lsp")
require("user.telescope")
require("user.project")
require("user.treesitter")
require("user.autopairs")
require("user.trouble")
require("user.comment")
require("user.neogen")
require("user.todo-comments")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine").setup()
require("user.noice")
require("user.toggleterm")
require("user.dashboard")
require("user.indentline")
require("user.neovide")
require("user.notify")
require("user.functions")
require("user.winbar")
-- require("user.tabby")
require("user.colorizer")
-- require "user.dap_install"
-- require "user.dap"
require("user.zen-mode")
require("user.hop")
-- require "user.neoscroll"
require("user.surround")
require("user.jaq")
require("user.dressing")
require("user.impatient")
require("user.illuminate")
require("user.cybu")
require("user.auto-session")
require("user.zk")
require("user.vim-slash")
require("user.spectre")
require("user.whichkey")
require("user.renamer")
--[[ require "user.shade" ]]
require("user.markdown-preview")
